spring.application.name=aidea

server.port=8080

# h2 dataBase url, 드라이버, 계정 설정
spring.datasource.url=jdbc:h2:mem:yjsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

# jpa 설정
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# h2 콘솔 설정
spring.h2.console.enabled=true
# localhost:8080/h2-console 로 접속 가능
spring.h2.console.path=/h2-console 

# spring security 설정
spring.security.user.name=admin
spring.security.user.password=1234